#!/bin/bash

for net in fc_1 fc_2 fc_3 fc_4 fc_5 fc_6 fc_7
do
	echo Evaluating network ${net}...
	for spec in `ls test_cases_prelim/${net}`
	do
		python code/verifier.py --net ${net} --spec test_cases_prelim/${net}/${spec} --labels test_cases_prelim/gt.txt
	done
done
